### ISSUE TITLE
For upload - how should i set another key? (like other dir and filename)

### ISSUE THREAD

**Issue by eladcandroid** [becem-gharbi/nuxt-s3#4]

**Comment by becem-gharbi** [comment]
I believe the location of the object (file) in bucket is irrelevant. Perhaps you can set a label (filename and dir) on the returned object's key and save both to database.

**Comment by eladcandroid** [comment]
@becem-gharbi I understand your logic. However, I would love to be able to transfer my own key. It helps me organize the file structure in S3.

**Comment by becem-gharbi** [comment]
Then i suggest relying on the filename. I mean you can define your own key (dir+filename.ext) and prepend it with a substring, e.g `key_{myKey}`. Before upload you should rename the file as the resulting string. 

This will be checked before calling `createKey` utility. If the filename starts with the string `key_`, the key will be extracted and used otherwise a new key will be generated. 

These changes should be made on [create](https://github.com/becem-gharbi/nuxt-s3/blob/3f50258b3f1ef4595452503bff9adb4cee4201b6/src/runtime/server/api/s3/object/create.ts#L33) and [update](https://github.com/becem-gharbi/nuxt-s3/blob/3f50258b3f1ef4595452503bff9adb4cee4201b6/src/runtime/server/api/s3/object/update.ts#L48).
